"""add is_main to project table

Revision ID: 1fbccb90037c
Revises: 50167f5c4a29
Create Date: 2026-06-17 04:29:46.057693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1fbccb90037c'
down_revision: Union[str, Sequence[str], None] = '50167f5c4a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_project', sa.Column('is_main', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_portfolio_project_is_main'), 'portfolio_project', ['is_main'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_project_is_main'), table_name='portfolio_project')
    op.drop_column('portfolio_project', 'is_main')
    # ### end Alembic commands ###
