"""Fix table inconsistency, add cascade deletes

Revision ID: 6ecc865967ad
Revises: f19eb2545ee2
Create Date: 2026-06-06 15:14:27.534026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ecc865967ad'
down_revision: Union[str, Sequence[str], None] = 'f19eb2545ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('portfolio_certificate_tag_certificate_id_fkey'), 'portfolio_certificate_tag', type_='foreignkey')
    op.drop_constraint(op.f('portfolio_certificate_tag_tag_id_fkey'), 'portfolio_certificate_tag', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_certificate_tag', 'portfolio_certificate', ['certificate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'portfolio_certificate_tag', 'portfolio_tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('portfolio_project_tag_project_id_fkey'), 'portfolio_project_tag', type_='foreignkey')
    op.drop_constraint(op.f('portfolio_project_tag_tag_id_fkey'), 'portfolio_project_tag', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_project_tag', 'portfolio_tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'portfolio_project_tag', 'portfolio_project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('portfolio_project_translation_language_code_fkey'), 'portfolio_project_translation', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_project_translation', 'portfolio_language', ['language_code'], ['code'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio_project_translation', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_project_translation_language_code_fkey'), 'portfolio_project_translation', 'portfolio_language', ['language_code'], ['code'])
    op.drop_constraint(None, 'portfolio_project_tag', type_='foreignkey')
    op.drop_constraint(None, 'portfolio_project_tag', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_project_tag_tag_id_fkey'), 'portfolio_project_tag', 'portfolio_tag', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('portfolio_project_tag_project_id_fkey'), 'portfolio_project_tag', 'portfolio_project', ['project_id'], ['id'])
    op.drop_constraint(None, 'portfolio_certificate_tag', type_='foreignkey')
    op.drop_constraint(None, 'portfolio_certificate_tag', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_certificate_tag_tag_id_fkey'), 'portfolio_certificate_tag', 'portfolio_tag', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('portfolio_certificate_tag_certificate_id_fkey'), 'portfolio_certificate_tag', 'portfolio_certificate', ['certificate_id'], ['id'])
    # ### end Alembic commands ###
