"""add_kelly_culummns

Revision ID: a3bc0fe6b0f8
Revises: bef1880650f2
Create Date: 2026-06-24 22:43:49.869781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3bc0fe6b0f8'
down_revision: Union[str, Sequence[str], None] = 'bef1880650f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statpitch_match_prediction', sa.Column('kelly_home', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_draw', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_away', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_over_1_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_under_1_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_over_2_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_under_2_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_over_3_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_under_3_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_over_1_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_under_1_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_over_2_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_under_2_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_over_3_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_under_3_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_over_1_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_under_1_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_over_2_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_under_2_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_over_3_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_under_3_5', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_btts_yes', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_btts_no', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_btts_yes', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_btts_no', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_btts_yes', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('kelly_btts_no', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('best_overall_bet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('best_overall_ev', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('best_overall_kelly', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statpitch_match_prediction', 'best_overall_kelly')
    op.drop_column('statpitch_match_prediction', 'best_overall_ev')
    op.drop_column('statpitch_match_prediction', 'best_overall_bet')
    op.drop_column('statpitch_match_prediction', 'kelly_btts_no')
    op.drop_column('statpitch_match_prediction', 'kelly_btts_yes')
    op.drop_column('statpitch_match_prediction', 'ev_btts_no')
    op.drop_column('statpitch_match_prediction', 'ev_btts_yes')
    op.drop_column('statpitch_match_prediction', 'odds_btts_no')
    op.drop_column('statpitch_match_prediction', 'odds_btts_yes')
    op.drop_column('statpitch_match_prediction', 'kelly_under_3_5')
    op.drop_column('statpitch_match_prediction', 'kelly_over_3_5')
    op.drop_column('statpitch_match_prediction', 'kelly_under_2_5')
    op.drop_column('statpitch_match_prediction', 'kelly_over_2_5')
    op.drop_column('statpitch_match_prediction', 'kelly_under_1_5')
    op.drop_column('statpitch_match_prediction', 'kelly_over_1_5')
    op.drop_column('statpitch_match_prediction', 'ev_under_3_5')
    op.drop_column('statpitch_match_prediction', 'ev_over_3_5')
    op.drop_column('statpitch_match_prediction', 'ev_under_2_5')
    op.drop_column('statpitch_match_prediction', 'ev_over_2_5')
    op.drop_column('statpitch_match_prediction', 'ev_under_1_5')
    op.drop_column('statpitch_match_prediction', 'ev_over_1_5')
    op.drop_column('statpitch_match_prediction', 'odds_under_3_5')
    op.drop_column('statpitch_match_prediction', 'odds_over_3_5')
    op.drop_column('statpitch_match_prediction', 'odds_under_2_5')
    op.drop_column('statpitch_match_prediction', 'odds_over_2_5')
    op.drop_column('statpitch_match_prediction', 'odds_under_1_5')
    op.drop_column('statpitch_match_prediction', 'odds_over_1_5')
    op.drop_column('statpitch_match_prediction', 'kelly_away')
    op.drop_column('statpitch_match_prediction', 'kelly_draw')
    op.drop_column('statpitch_match_prediction', 'kelly_home')
    # ### end Alembic commands ###
