"""add_statpitch_schema

Revision ID: bef1880650f2
Revises: 9c1ad9f14faf
Create Date: 2026-06-23 23:48:19.731668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bef1880650f2'
down_revision: Union[str, Sequence[str], None] = '9c1ad9f14faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statpitch_match_prediction', sa.Column('home_flag_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('away_flag_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_home', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_draw', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('odds_away', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_home', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_draw', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('ev_away', sa.Float(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('best_bet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('statpitch_match_prediction', sa.Column('actual_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statpitch_match_prediction', 'actual_result')
    op.drop_column('statpitch_match_prediction', 'best_bet')
    op.drop_column('statpitch_match_prediction', 'ev_away')
    op.drop_column('statpitch_match_prediction', 'ev_draw')
    op.drop_column('statpitch_match_prediction', 'ev_home')
    op.drop_column('statpitch_match_prediction', 'odds_away')
    op.drop_column('statpitch_match_prediction', 'odds_draw')
    op.drop_column('statpitch_match_prediction', 'odds_home')
    op.drop_column('statpitch_match_prediction', 'away_flag_url')
    op.drop_column('statpitch_match_prediction', 'home_flag_url')
    # ### end Alembic commands ###
