"""Rename and modify certificate table to course and new certification table

Revision ID: c8be1bc61672
Revises: 
Create Date: 2026-06-09 02:31:36.130965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8be1bc61672'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('portfolio_course_validation_serial_key'), 'portfolio_course', type_='unique')
    op.drop_column('portfolio_course', 'isMain')
    op.drop_column('portfolio_course', 'validation_serial')
    op.drop_column('portfolio_course', 'isVerified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_course', sa.Column('isVerified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('portfolio_course', sa.Column('validation_serial', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('portfolio_course', sa.Column('isMain', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('portfolio_course_validation_serial_key'), 'portfolio_course', ['validation_serial'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
