"""Add new tables and edit Project, ProjectTranslation and Certificate

Revision ID: f19eb2545ee2
Revises: 
Create Date: 2026-06-06 15:00:18.301101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f19eb2545ee2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_category_name'), 'portfolio_category', ['name'], unique=True)
    op.create_table('portfolio_difficulty_level',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_difficulty_level_name'), 'portfolio_difficulty_level', ['name'], unique=True)
    op.create_table('portfolio_language',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portfolio_project_type',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_project_type_name'), 'portfolio_project_type', ['name'], unique=True)
    op.add_column('portfolio_certificate', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'portfolio_certificate', 'portfolio_category', ['category_id'], ['id'])
    op.add_column('portfolio_project', sa.Column('project_type_id', sa.Integer(), nullable=False))
    op.add_column('portfolio_project', sa.Column('difficulty_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'portfolio_project', 'portfolio_project_type', ['project_type_id'], ['id'])
    op.create_foreign_key(None, 'portfolio_project', 'portfolio_difficulty_level', ['difficulty_id'], ['id'])
    op.drop_column('portfolio_project', 'type')
    op.drop_column('portfolio_project', 'difficulty')
    op.create_foreign_key(None, 'portfolio_project_translation', 'portfolio_language', ['language_code'], ['code'])
    op.drop_column('portfolio_project_translation', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_project_translation', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'portfolio_project_translation', type_='foreignkey')
    op.add_column('portfolio_project', sa.Column('difficulty', postgresql.ENUM('JUNIOR', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficultylevel'), autoincrement=False, nullable=False))
    op.add_column('portfolio_project', sa.Column('type', postgresql.ENUM('WEB', 'MOBILE', 'DESKTOP', 'COMPONENT', 'API', name='projecttype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'portfolio_project', type_='foreignkey')
    op.drop_constraint(None, 'portfolio_project', type_='foreignkey')
    op.drop_column('portfolio_project', 'difficulty_id')
    op.drop_column('portfolio_project', 'project_type_id')
    op.drop_constraint(None, 'portfolio_certificate', type_='foreignkey')
    op.drop_column('portfolio_certificate', 'category_id')
    op.drop_index(op.f('ix_portfolio_project_type_name'), table_name='portfolio_project_type')
    op.drop_table('portfolio_project_type')
    op.drop_table('portfolio_language')
    op.drop_index(op.f('ix_portfolio_difficulty_level_name'), table_name='portfolio_difficulty_level')
    op.drop_table('portfolio_difficulty_level')
    op.drop_index(op.f('ix_portfolio_category_name'), table_name='portfolio_category')
    op.drop_table('portfolio_category')
    # ### end Alembic commands ###
